apiVersion: v1
kind: Service
metadata:
  name: lb-finance
  labels:
    app: lb-finance
spec:
  selector:
    app: lb-finance
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-finance
spec:
  selector:
    matchLabels:
      app: lb-finance
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 15
  template:
    metadata:
      name: lb-finance
      labels:
        app: lb-finance
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - lb-finance
                topologyKey: 'kubernetes.io/hostname'
      containers:
        - name: lb-finance
          image: registry-gitlab.arimaclanka.com/lb-finance/2024-annual-report-web/frontend/annual-report-web
          imagePullPolicy: Always
          command: ['/bin/sh', '-c', 'yarn run start']
          envFrom:
            - configMapRef:
                name: lb-finance-env
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lb-finance-env
  namespace: web
data:
  API_BASE_URL: https://lb-finance-cms.dev.com
