# Project identification
sonar.projectKey=lb_finance_web_project
sonar.projectName=LB Finance Project
sonar.projectVersion=SONAR_VERSION

# Source code and language settings
sonar.sources=./app,./utility
sonar.language=ts
sonar.sourceEncoding=UTF-8

# TypeScript settings
sonar.typescript.tsconfigPath=tsconfig.json

# Exclude files and directories
sonar.exclusions=**/node_modules/**, **/__mocks__/**, **/tests__/**, **/*.test.tsx, **/*.test.ts, ./components/*, ./app/[lang]/annual-report/**

# Coverage report paths
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# SCM settings
sonar.scm.provider=git

# Disable analysis for languages not used in the project
sonar.java.binaries=-
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
sonar.html.file.suffixes=-
sonar.css.file.suffixes=-
sonar.java.file.suffixes=-
